package com.example.quant.crypto.dto;

import com.example.quant.market.DirectionBias;
import com.example.quant.market.MarketType;
import com.example.quant.risk.RiskLevel;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

public record ContractCandidate(
        MarketType marketType,
        String instId,
        String baseCurrency,
        String quoteCurrency,
        BigDecimal lastPrice,
        BigDecimal changePercent24h,
        BigDecimal changePercent5m,
        BigDecimal volume24h,
        BigDecimal volumeSpikeRatio,
        BigDecimal fundingRate,
        BigDecimal openInterest,
        BigDecimal openInterestChange,
        DirectionBias trendDirection,
        BigDecimal volatility,
        int score,
        ContractFactorScore factorScore,
        BigDecimal entryPrice,
        BigDecimal stopLossPrice,
        BigDecimal takeProfitPrice,
        int suggestedLeverage,
        BigDecimal riskRewardRatio,
        BigDecimal spreadBps,
        BigDecimal bidDepthUsdt,
        BigDecimal askDepthUsdt,
        BigDecimal estimatedSlippageBps,
        DirectionBias btcTrend,
        DirectionBias ethTrend,
        RiskLevel marketRiskLevel,
        List<String> candidateReasonList,
        List<String> riskTagList,
        Instant createdAt,
        ContractSignalType signalType,
        String action,
        String entryType,
        BigDecimal todayChangePct,
        BigDecimal atrPct20m,
        BigDecimal stopLossPct,
        BigDecimal finalRankScore,
        ContractScoreBreakdown scoreBreakdown,
        ContractKlineAnalysis klineAnalysis,
        ContractNewsRiskAnalysis newsAnalysis
) {
    public ContractCandidate(
            MarketType marketType,
            String instId,
            String baseCurrency,
            String quoteCurrency,
            BigDecimal lastPrice,
            BigDecimal changePercent24h,
            BigDecimal changePercent5m,
            BigDecimal volume24h,
            BigDecimal volumeSpikeRatio,
            BigDecimal fundingRate,
            BigDecimal openInterest,
            BigDecimal openInterestChange,
            DirectionBias trendDirection,
            BigDecimal volatility,
            int score,
            ContractFactorScore factorScore,
            BigDecimal entryPrice,
            BigDecimal stopLossPrice,
            BigDecimal takeProfitPrice,
            int suggestedLeverage,
            BigDecimal riskRewardRatio,
            BigDecimal spreadBps,
            BigDecimal bidDepthUsdt,
            BigDecimal askDepthUsdt,
            BigDecimal estimatedSlippageBps,
            DirectionBias btcTrend,
            DirectionBias ethTrend,
            RiskLevel marketRiskLevel,
            List<String> candidateReasonList,
            List<String> riskTagList,
            Instant createdAt
    ) {
        this(
                marketType,
                instId,
                baseCurrency,
                quoteCurrency,
                lastPrice,
                changePercent24h,
                changePercent5m,
                volume24h,
                volumeSpikeRatio,
                fundingRate,
                openInterest,
                openInterestChange,
                trendDirection,
                volatility,
                score,
                factorScore,
                entryPrice,
                stopLossPrice,
                takeProfitPrice,
                suggestedLeverage,
                riskRewardRatio,
                spreadBps,
                bidDepthUsdt,
                askDepthUsdt,
                estimatedSlippageBps,
                btcTrend,
                ethTrend,
                marketRiskLevel,
                candidateReasonList,
                riskTagList,
                createdAt,
                trendDirection == DirectionBias.BEARISH ? ContractSignalType.TREND_SHORT : ContractSignalType.STRONG_LONG,
                score >= 80 ? "AUTO_TRADE_ALLOWED" : "WAIT_CONFIRM",
                "LIMIT",
                changePercent24h,
                volatility == null ? BigDecimal.ZERO : volatility.multiply(BigDecimal.valueOf(100)),
                BigDecimal.ZERO,
                BigDecimal.valueOf(score),
                new ContractScoreBreakdown(score, score, score, score, score, score, factorScore.newsRiskScore() * 100 / 7),
                ContractKlineAnalysis.unavailable("LEGACY_ANALYSIS"),
                ContractNewsRiskAnalysis.low()
        );
    }
}
