package com.example.quant.order;

public enum OrderStatus {
    CREATED,
    PENDING_CONFIRM,
    BUDGET_RESERVED,
    CONFIRMING,
    CONFIRMED,
    SUBMITTING,
    SUBMITTED,
    UNKNOWN_SUBMIT_STATUS,
    ENTRY_FILLED,
    PROTECTION_PENDING,
    PROTECTION_SUBMITTED,
    ACTIVE,
    ACTIVE_WITH_TP_WARNING,
    PROTECTION_FAILED,
    EXECUTED,
    CANCELLED,
    EXPIRED,
    REJECTED,
    FAILED,
    CLOSED,
    EMERGENCY_ATTENTION_REQUIRED
}
