package com.example.quant.agent.event;

public enum TradeEventType {
    AUTO_CANDIDATE_SKIPPED,
    PLAN_CREATED,
    BUDGET_RESERVED,
    ENTRY_SUBMITTED,
    ENTRY_SUBMIT_UNKNOWN,
    ENTRY_FILLED,
    ENTRY_PARTIAL_FILLED,
    ENTRY_TIMEOUT_CANCELLED,
    PROTECTION_SUBMITTED,
    PROTECTION_FAILED,
    SIDEWAYS_TP_REPLACED,
    MAX_HOLD_CLOSE_SUBMITTED,
    MANUAL_CLOSE_SUBMITTED,
    CLOSE_CONFIRMED,
    BUDGET_RELEASED,
    RECOVERY_FAILED
}
