CREATE TABLE IF NOT EXISTS pending_order_state (
    id VARCHAR(36) PRIMARY KEY,
    market_type VARCHAR(32) NOT NULL,
    inst_id VARCHAR(64) NOT NULL,
    action VARCHAR(32) NOT NULL,
    side VARCHAR(16),
    pos_side VARCHAR(16),
    order_type VARCHAR(32),
    price DECIMAL(30, 12),
    size_value DECIMAL(30, 12),
    leverage INT,
    td_mode VARCHAR(32),
    stop_loss_price DECIMAL(30, 12),
    take_profit_price DECIMAL(30, 12),
    max_loss_amount DECIMAL(30, 12),
    margin_amount DECIMAL(30, 12),
    budget_reservation_id VARCHAR(36),
    budget_allocation_json TEXT,
    client_order_id VARCHAR(64),
    risk_reward_ratio DECIMAL(18, 8),
    signal_score INT,
    funding_rate DECIMAL(18, 8),
    volatility DECIMAL(18, 8),
    volume_24h DECIMAL(30, 12),
    trade_plan_id VARCHAR(36),
    confirm_token VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    user_confirmed BOOLEAN DEFAULT FALSE,
    confirmed_at TIMESTAMP,
    submitted_at TIMESTAMP,
    executed_at TIMESTAMP,
    external_order_id VARCHAR(128),
    reject_reason TEXT,
    created_at TIMESTAMP NOT NULL,
    expire_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_pending_order_state_status (status),
    INDEX idx_pending_order_state_symbol_side (inst_id, pos_side),
    INDEX idx_pending_order_state_client_order (client_order_id),
    INDEX idx_pending_order_state_budget (budget_reservation_id)
);
