CREATE TABLE IF NOT EXISTS trade_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_plan_id VARCHAR(36),
    pending_order_id VARCHAR(36),
    order_role VARCHAR(32) NOT NULL,
    inst_id VARCHAR(64) NOT NULL,
    side VARCHAR(16) NOT NULL,
    pos_side VARCHAR(16),
    ord_type VARCHAR(32) NOT NULL,
    td_mode VARCHAR(16) NOT NULL,
    size_value DECIMAL(30, 12),
    price DECIMAL(30, 12),
    reduce_only BOOLEAN NOT NULL DEFAULT FALSE,
    cl_ord_id VARCHAR(64),
    okx_ord_id VARCHAR(128),
    okx_state VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_trade_order_cl_ord_id (cl_ord_id),
    INDEX idx_trade_order_trade_plan_id (trade_plan_id),
    INDEX idx_trade_order_pending_order_id (pending_order_id),
    INDEX idx_trade_order_status (status),
    INDEX idx_trade_order_inst_id (inst_id)
);
