CREATE TABLE IF NOT EXISTS auto_trade_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    status VARCHAR(32) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL DEFAULT 'SCHEDULER',
    inst_id VARCHAR(64),
    trade_plan_id VARCHAR(36),
    pending_order_id VARCHAR(36),
    okx_order_id VARCHAR(128),
    candidate_count INT NOT NULL DEFAULT 0,
    candidate_score INT,
    trend_direction VARCHAR(32),
    last_price DECIMAL(30, 12),
    risk_reward_ratio DECIMAL(18, 8),
    spread_bps DECIMAL(18, 8),
    bid_depth_usdt DECIMAL(30, 12),
    ask_depth_usdt DECIMAL(30, 12),
    market_risk_level VARCHAR(32),
    message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_auto_trade_record_created_at (created_at),
    INDEX idx_auto_trade_record_status (status),
    INDEX idx_auto_trade_record_inst_id (inst_id),
    INDEX idx_auto_trade_record_status_created_at (status, created_at)
);
